# ----------------------- #
#      Main Configs       #
# ----------------------- #


title: Studio Spielraum 
email: martin@studio-spielram.de
author: Martin Pflieger
description: Erfindung neuer Spielideen sowie Beratung als Spieleredakteur 

copyright: 'Copyright &copy; Studio-Spielraum. All Rights Reserved.'


# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: none
baseurl: ""
url: "https://Studio-Spielraum.github.io"

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: instagram
    url: https://instagram.com/raise_uav
  - title: youtube
    url: https://youtube.com/BKLronin
  - title: thingiverse
    url: https://thingiverse.com/kleingeist/designs
